const HTTP_STATUS_OK = 200;
const HTTP_STATUS_CREATED = 201;
const HTTP_STATUS_ACCEPTED = 202;
const HTTP_STATUS_NO_CONTENT = 204;
const HTTP_STATUS_MOVED_PERMANENTLY = 301;
const HTTP_STATUS_FOUND = 302;
const HTTP_STATUS_NOT_MODIFIED = 304;
const HTTP_STATUS_BAD_REQUEST = 400;
const HTTP_STATUS_UNAUTHORIZED = 401;
const HTTP_STATUS_FORBIDDEN = 403;
const HTTP_STATUS_NOT_FOUND = 404;
const HTTP_STATUS_METHOD_NOT_ALLOWED = 405;
const HTTP_STATUS_CONFLICT = 409;
const HTTP_STATUS_UNPROCESSABLE_ENTITY = 422;
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
const HTTP_STATUS_NOT_IMPLEMENTED = 501;
const HTTP_STATUS_BAD_GATEWAY = 502;
const HTTP_STATUS_SERVICE_UNAVAILABLE = 503;
const HTTP_STATUS_GATEWAY_TIMEOUT = 504;

export enum HttpStatusCode {
    OK = HTTP_STATUS_OK,
    CREATED = HTTP_STATUS_CREATED,
    ACCEPTED = HTTP_STATUS_ACCEPTED,
    NO_CONTENT = HTTP_STATUS_NO_CONTENT,
    MOVED_PERMANENTLY = HTTP_STATUS_MOVED_PERMANENTLY,
    FOUND = HTTP_STATUS_FOUND,
    NOT_MODIFIED = HTTP_STATUS_NOT_MODIFIED,
    BAD_REQUEST = HTTP_STATUS_BAD_REQUEST,
    UNAUTHORIZED = HTTP_STATUS_UNAUTHORIZED,
    FORBIDDEN = HTTP_STATUS_FORBIDDEN,
    NOT_FOUND = HTTP_STATUS_NOT_FOUND,
    METHOD_NOT_ALLOWED = HTTP_STATUS_METHOD_NOT_ALLOWED,
    CONFLICT = HTTP_STATUS_CONFLICT,
    UNPROCESSABLE_ENTITY = HTTP_STATUS_UNPROCESSABLE_ENTITY,
    INTERNAL_SERVER_ERROR = HTTP_STATUS_INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED = HTTP_STATUS_NOT_IMPLEMENTED,
    BAD_GATEWAY = HTTP_STATUS_BAD_GATEWAY,
    SERVICE_UNAVAILABLE = HTTP_STATUS_SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT = HTTP_STATUS_GATEWAY_TIMEOUT,
}

export enum HttpStatusDescription {
    OK = 'OK',
    CREATED = 'Created',
    ACCEPTED = 'Accepted',
    NO_CONTENT = 'No Content',
    MOVED_PERMANENTLY = 'Moved Permanently',
    FOUND = 'Found',
    NOT_MODIFIED = 'Not Modified',
    BAD_REQUEST = 'Bad Request',
    UNAUTHORIZED = 'Unauthorized',
    FORBIDDEN = 'Forbidden',
    NOT_FOUND = 'Not Found',
    METHOD_NOT_ALLOWED = 'Method Not Allowed',
    CONFLICT = 'Conflict',
    UNPROCESSABLE_ENTITY = 'Unprocessable Entity',
    INTERNAL_SERVER_ERROR = 'Internal Server Error',
    NOT_IMPLEMENTED = 'Not Implemented',
    BAD_GATEWAY = 'Bad Gateway',
    SERVICE_UNAVAILABLE = 'Service Unavailable',
    GATEWAY_TIMEOUT = 'Gateway Timeout',
}
